### ISSUE TITLE
ImportError: cannot import name '_api' from partially initialized module 'matplotlib

### ISSUE THREAD

**Issue by pk-1196** [VirajDeshwal/YOLOv5#1]
ImportError: cannot import name '_api' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\prave\anaconda3\lib\site-packages\matplotlib\__init__.py)

getting above error while running main_file.py

**Comment by VirajDeshwal** [comment]
@pk-1196 The problem is with your matplotlib installation. The solution to your problem is mentioned here -> https://stackoverflow.com/questions/63187644/import-error-cannot-import-name-ft2font-from-partially-initialized-module-ma/63187840#63187840
